#Read in the SRADump generated by eSearch & eFetch 
#Return only sample accs with TaxID 10116 
SRADump<-read.table("/home4/rich01e/sraData/SRDumpTax.txt",header=TRUE, sep=",", 
              quote = "", na.strings = c("", "NA", "n/a"), fill = T)

SRADumpRat <- SRADump[ which(SRADump$TaxID==10116),]
as.name(SRADumpRat$Run)
SRADumpRat$Run <- as.character(SRADumpRat$Run)
write.table(paste(SRADumpRat$Run), file = "RatSampleAccs", row.names=F,col.names=F,quote=FALSE)

